# ---------------------------------------------------------------------------
# Shared background blocks — reused across multiple prompt use cases
# ---------------------------------------------------------------------------

BRANE_CONTEXT = """--- BACKGROUND: WHAT IS BRANE ---
Brane is a federated workflow orchestration framework. It allows computation to run across multiple institutions (called worker nodes) without any raw data ever leaving those institutions. Instead of centralising data, Brane sends containerised functions to each site, runs them locally on the data there, and only returns aggregated results. This preserves data privacy and satisfies legal constraints like GDPR.

Each Brane deployment has one central coordinator node and multiple worker nodes. The central node plans and orchestrates the workflow but never holds raw data. Worker nodes each represent one participant institution (e.g. a hospital) and hold their own local datasets."""


BRANESCRIPT_CONSTRUCTS = """--- BACKGROUND: WHAT IS BRANESCRIPT ---
BraneScript is the domain-specific language used to describe a federated workflow. It is automatically generated by the Integrator from the project configuration and participant policies collected in BraneHub. The project owner does not write BraneScript themselves — this script was generated on their behalf.

Key BraneScript constructs and what they mean:

- import <package>: Loads the computation package that will run at each participant site. This package contains the functions that process the local data.

- new Data { name := "dataset-name" }: References the local dataset held at a participant site. The dataset never leaves that site — only the result of processing it does.

- #[on("node-name")]: A hard enforcement annotation. It tells the Brane planner that the following function MUST execute on the named worker node, and nowhere else. This is the primary mechanism that guarantees data locality — the computation physically runs at the institution that owns the data, not on a central server. If this constraint cannot be satisfied, the workflow will not run.

- #[tag("key.value")]: A soft policy annotation at the statement level. It attaches structured metadata (e.g. the identifiability level of the data being processed) to a specific function call. This metadata is evaluated by the eFLINT policy checker at the worker node before the function is allowed to run.

- #![wf_tag("key.value")]: A workflow-level policy annotation. It applies structured metadata to the entire workflow (e.g. overall data sensitivity level or legal basis). This is checked at the workflow planning stage.

- let result := function(data): Calls a function from the imported package on the local data and stores the result. The result is a statistical aggregate, not raw data.

- return result: Returns the final combined result from the workflow to the requester."""




NOTE_GENERATION_ROLE = """You are an expert assistant helping domain scientists and non-technical project owners understand automatically generated federated learning workflows. Your job is to write a clear, thorough, plain-English explanation of a generated workflow so that the project owner can make an informed decision about whether to approve or reject it."""


TRACEABILITY_REPORT_EXPLANATION = """--- BACKGROUND: WHAT IS THE TRACEABILITY REPORT ---
The traceability report is a structured audit document generated alongside the BraneScript. It records exactly how every policy decision from BraneHub was translated into a BraneScript construct. Each entry in the report maps one policy field (from the participant's onboarding questionnaire or the project configuration) to the specific line in the BraneScript it produced.

Fields in each traceability report entry:
- participant_node: The Brane worker node name for this participant (e.g. "worker1"). Null for workflow-level entries that apply to the whole workflow.
- participant_user_id: The BraneHub user ID of this participant. Null for workflow-level entries.
- policy_field: The name of the policy field from BraneHub (e.g. "brane_node", "identifiability", "data_sensitivity").
- policy_value: The value of that policy field for this participant or project (e.g. "Pseudonymized", "High").
- generated_construct: The exact BraneScript construct that was generated to enforce this policy (e.g. '#[on("worker1")]'). Null if the field was flagged as unenforced.
- line: The line number in the BraneScript where this construct appears.
- flagged: True if this policy field could not be encoded as a BraneScript construct. Flagged fields are documented but not computationally enforced in the generated script — they represent governance requirements that must be enforced through other means (e.g. organisational agreements or manual checks).
- note/reason: An explanation for why an entry was flagged, if applicable."""


NOTE_GENERATION_TASK = """--- YOUR TASK ---
Given the BraneScript and traceability report below, write a thorough plain-English explanation for the project owner. Structure your response as follows:

1. What this workflow does: Explain in simple terms what computation will run, across which participant sites, and what result will be produced.

2. How each participant's data is protected: For each participant, explain which node their computation runs on, what their data is called, and what policy annotations protect them.

3. How project-level policies are enforced: Explain what workflow-level tags are present and what governance requirements they represent.

4. Traceability — policy decisions explained: Walk through the traceability report entries and explain in plain English what each policy field means and why the generated construct correctly enforces it.

5. Flagged fields — what could not be automatically enforced: List and explain any flagged entries. Be clear that these fields are documented but not computationally enforced in the script, and explain what the project owner or institution must do to ensure compliance.

6. What to expect as output: Describe what the workflow will return when it runs successfully.

Write in plain English. No markdown formatting. Be thorough but clear. A domain scientist with no programming background should be able to read this and understand exactly what the workflow will do and why it was generated the way it was."""


NOTE_GENERATION_USER = """BraneScript:
{branescript}

Traceability Report (JSON):
{traceability_report}"""




POLICY_FIELDS_REFERENCE = """--- KNOWN POLICY FIELDS ---
The following policy fields can be extracted from free text. Each field has a fixed set of allowed values that must be matched exactly (case-sensitive):

- identifiability: one of ["Identified", "PseudonymizedBySource", "Anonymized"]
  Describes how personally identifiable the data is. "Identified" means the dataset contains direct personal identifiers. "PseudonymizedBySource" means identifiers have been replaced with pseudonyms by the data provider before sharing. "Anonymized" means all personal identifiers have been removed and re-identification is not reasonably possible.

- data_sensitivity: one of ["low", "medium", "high"]
  Describes the overall sensitivity level of the data. Typically "high" for health or clinical data, "medium" for aggregated or lightly processed data, "low" for fully public or synthetic data.

- legal_basis: one of ["consent", "legitimate_interest", "legal_obligation", "vital_interest", "public_task"]
  The legal basis under which the data may be processed (GDPR Art. 6). "consent" means explicit participant consent was obtained. "legitimate_interest" means processing is necessary for a legitimate organisational purpose. "legal_obligation" means required by law. "vital_interest" means necessary to protect someone's life. "public_task" means required to perform an official function.

Only extract a claim if the free text clearly and unambiguously implies one of these specific values. Do not infer, guess, or extrapolate."""


FREE_TEXT_EXTRACTION_TASK = """--- YOUR TASK ---
You are a policy extraction assistant for federated learning research workflows.

Given free-text answers from a research participant's onboarding questionnaire, extract any structured policy claims that map to the known policy fields listed above.

Return a JSON array. Each element must have exactly these keys:
  - "source_field": which input field the claim was found in
  - "policy_field": the policy field name (must be one of the known fields above)
  - "policy_value": the extracted value (must match an allowed value exactly, case-sensitive)
  - "confidence": "high", "medium", or "low"

Rules:
- Only include claims where the text clearly implies a known allowed value.
- Do not invent or extrapolate values beyond what is stated.
- If the same policy_field is implied multiple times, include only the highest-confidence claim.
- If no claims can be extracted, return [].
- Return only valid JSON — no prose, no explanation, no markdown code fences."""


FREE_TEXT_EXTRACTION_USER = """Free-text inputs for this participant:
{free_text_inputs}"""
