# ---------------------------------------------------------------------------
# Shared background blocks — reused across multiple prompt use cases
# ---------------------------------------------------------------------------

BRANE_CONTEXT = """--- BACKGROUND: WHAT IS BRANE ---
Brane is a federated workflow orchestration framework. It allows computation to run across multiple institutions (called worker nodes) without any raw data ever leaving those institutions. Instead of centralising data, Brane sends containerised functions to each site, runs them locally on the data there, and only returns aggregated results. This preserves data privacy and satisfies legal constraints like GDPR.

Each Brane deployment has one central coordinator node and multiple worker nodes. The central node plans and orchestrates the workflow but never holds raw data. Worker nodes each represent one participant institution (e.g. a hospital) and hold their own local datasets."""


BRANESCRIPT_CONSTRUCTS = """--- BACKGROUND: WHAT IS BRANESCRIPT ---
BraneScript is the domain-specific language used to describe a federated workflow. It is automatically generated by the Integrator from the project configuration and participant policies collected in BraneHub. The project owner does not write BraneScript themselves — this script was generated on their behalf.

Key BraneScript constructs and what they mean:

- import <package>: Loads the computation package that will run at each participant site. This package contains the functions that process the local data.

- new Data { name := "dataset-name" }: References the local dataset held at a participant site. The dataset never leaves that site — only the result of processing it does.

- #[on("node-name")]: A hard enforcement annotation. It tells the Brane planner that the following function MUST execute on the named worker node, and nowhere else. This is the primary mechanism that guarantees data locality — the computation physically runs at the institution that owns the data, not on a central server. If this constraint cannot be satisfied, the workflow will not run.

- #[tag("key.value")]: A soft policy annotation at the statement level. It attaches structured metadata (e.g. the identifiability level of the data being processed) to a specific function call. This metadata is evaluated by the eFLINT policy checker at the worker node before the function is allowed to run.

- #![wf_tag("key.value")]: A workflow-level policy annotation. It applies structured metadata to the entire workflow (e.g. overall data sensitivity level or legal basis). This is checked at the workflow planning stage.

- let result := function(data): Calls a function from the imported package on the local data and stores the result. The result is a statistical aggregate, not raw data.

- return result: Returns the final combined result from the workflow to the requester."""




NOTE_GENERATION_ROLE = """You are an expert assistant helping domain scientists and non-technical project owners understand automatically generated federated learning workflows. Your job is to write a clear, thorough, plain-English explanation of a generated workflow so that the project owner can make an informed decision about whether to approve or reject it."""


TRACEABILITY_REPORT_EXPLANATION = """--- BACKGROUND: WHAT IS THE TRACEABILITY REPORT ---
The traceability report is a structured audit document generated alongside the BraneScript. It records exactly how every policy decision from BraneHub was translated into a BraneScript construct. Each entry in the report maps one policy field (from the participant's onboarding questionnaire or the project configuration) to the specific line in the BraneScript it produced.

Fields in each traceability report entry:
- participant_node: The Brane worker node name for this participant (e.g. "worker1"). Null for workflow-level entries that apply to the whole workflow.
- participant_user_id: The BraneHub user ID of this participant. Null for workflow-level entries.
- policy_field: The name of the policy field from BraneHub (e.g. "brane_node", "identifiability", "data_sensitivity").
- policy_value: The value of that policy field for this participant or project (e.g. "Pseudonymized", "High").
- generated_construct: The exact BraneScript construct that was generated to enforce this policy (e.g. '#[on("worker1")]'). Null if the field was flagged as unenforced.
- line: The line number in the BraneScript where this construct appears.
- flagged: True if this policy field could not be encoded as a BraneScript construct. Flagged fields are documented but not computationally enforced in the generated script — they represent governance requirements that must be enforced through other means (e.g. organisational agreements or manual checks).
- note/reason: An explanation for why an entry was flagged, if applicable."""


NOTE_GENERATION_TASK = """--- YOUR TASK ---
Given the BraneScript and traceability report below, write a thorough plain-English explanation for the project owner. Structure your response as follows:

1. What this workflow does: Explain in simple terms what computation will run, across which participant sites, and what result will be produced.

2. How each participant's data is protected: For each participant, explain which node their computation runs on, what their data is called, and what policy annotations protect them.

3. How project-level policies are enforced: Explain what workflow-level tags are present and what governance requirements they represent.

4. Traceability — policy decisions explained: Walk through the traceability report entries and explain in plain English what each policy field means and why the generated construct correctly enforces it.

5. Flagged fields — what could not be automatically enforced: List and explain any flagged entries. Be clear that these fields are documented but not computationally enforced in the script, and explain what the project owner or institution must do to ensure compliance.

6. What to expect as output: Describe what the workflow will return when it runs successfully.

Write in plain English. No markdown formatting. Be thorough but clear. A domain scientist with no programming background should be able to read this and understand exactly what the workflow will do and why it was generated the way it was."""


NOTE_GENERATION_USER = """BraneScript:
{branescript}

Traceability Report (JSON):
{traceability_report}"""




POLICY_FIELDS_REFERENCE = """--- KNOWN POLICY FIELDS ---
The following policy fields can be extracted from free text. Each field has a fixed set of allowed values that must be matched exactly (case-sensitive):

- identifiability: one of ["Identified", "PseudonymizedBySource", "Anonymized"]
  Describes how personally identifiable the data is. "Identified" means the dataset contains direct personal identifiers. "PseudonymizedBySource" means identifiers have been replaced with pseudonyms by the data provider before sharing. "Anonymized" means all personal identifiers have been removed and re-identification is not reasonably possible.

- data_sensitivity: one of ["low", "medium", "high"]
  Describes the overall sensitivity level of the data. Typically "high" for health or clinical data, "medium" for aggregated or lightly processed data, "low" for fully public or synthetic data.

- legal_basis: one of ["consent", "legitimate_interest", "legal_obligation", "vital_interest", "public_task"]
  The legal basis under which the data may be processed (GDPR Art. 6). "consent" means explicit participant consent was obtained. "legitimate_interest" means processing is necessary for a legitimate organisational purpose. "legal_obligation" means required by law. "vital_interest" means necessary to protect someone's life. "public_task" means required to perform an official function.

Only extract a claim if the free text clearly and unambiguously implies one of these specific values. Do not infer, guess, or extrapolate."""


FREE_TEXT_EXTRACTION_TASK = """--- YOUR TASK ---
You are a policy extraction assistant for federated learning research workflows.

Given free-text answers from a research participant's onboarding questionnaire, extract any structured policy claims that map to the known policy fields listed above.

Return a JSON array. Each element must have exactly these keys:
  - "source_field": which input field the claim was found in
  - "policy_field": the policy field name (must be one of the known fields above)
  - "policy_value": the extracted value (must match an allowed value exactly, case-sensitive)
  - "confidence": "high", "medium", or "low"

Rules:
- Only include claims where the text clearly implies a known allowed value.
- Do not invent or extrapolate values beyond what is stated.
- If the same policy_field is implied multiple times, include only the highest-confidence claim.
- If no claims can be extracted, return [].
- Return only valid JSON — no prose, no explanation, no markdown code fences."""


FREE_TEXT_EXTRACTION_USER = """Free-text inputs for this participant:
{free_text_inputs}"""


LLM_GENERATOR_SYSTEM = """You are a BraneScript workflow generator for federated learning projects.

""" + BRANESCRIPT_CONSTRUCTS + """

--- EXACT FORMAT RULES ---
You MUST follow this exact structure. Any deviation will cause a runtime error.

RULE 1: Every statement or annotation is on its own line. Never put two annotations or a statement and annotation on the same line.

RULE 2: #![wf_tag()] lines have NO semicolon. Write exactly:
#![wf_tag("sensitivity.High")]
NOT:
#![wf_tag("sensitivity.High")];   <- WRONG, no semicolon allowed

RULE 3: #[on()] and #[tag()] are each on their own separate line. Write:
#[on("worker1")]
#[tag("identifiability.Pseudonymized")]
let stats_1 := compute_local_stats(data_1);
NOT:
#[on("worker1")] #[tag("identifiability.Pseudonymized")] let stats_1 := ...   <- WRONG

RULE 4: The exact order for each participant block is:
#[on("node-name")]
#[tag("identifiability.VALUE")]
let result_N := local_function(data_N);

RULE 5: The exact order for the combine block is:
#[on("coordinator-node")]
let result := combine_function(result_1, result_2, ...);

--- COMPLETE EXAMPLE ---
Here is a correct example for a 2-participant project:

import mypackage;

#![wf_tag("sensitivity.High")]
#![wf_tag("jurisdiction.EU")]

let data_1 := new Data { name := "dataset-site1" };
let data_2 := new Data { name := "dataset-site2" };

#[on("site1")]
#[tag("identifiability.Pseudonymized")]
let stats_1 := local_fn(data_1);

#[on("site2")]
#[tag("identifiability.Anonymized")]
let stats_2 := local_fn(data_2);

#[on("central")]
let result := combine_fn(stats_1, stats_2);

return result;

--- GENERATION RULES ---
1. Start with: import <package>;
2. Place all #![wf_tag()] lines immediately after import, one per line, NO semicolons.
3. Declare all datasets: let data_N := new Data { name := "dataset-name" };
4. For each participant: one #[on()] line, then one #[tag()] per tag, each on its own line, then the let statement.
5. For the combine step: #[on("coordinator")] on its own line, then the combine let statement.
6. End with: return <result>;
7. Return ONLY the BraneScript. No markdown, no comments, no explanation."""


LLM_GENERATOR_USER = """Generate a complete BraneScript workflow for the following federated project.

Package: {package}
Local function (runs at each participant): {local_function}
Combine function (runs at coordinator): {combine_function}
Coordinator node: {coordinator_node}

Participants:
{participants_block}

Workflow-level policy tags to include (one per line, NO semicolons):
{wf_tags_block}

Generate the BraneScript now:"""


LLM_GENERATOR_RETRY_SUFFIX = """

--- PREVIOUS ATTEMPT FAILED VALIDATION ---
The following rules failed. Fix them in your new response:
{failures}

Generate a corrected BraneScript now:"""


# ---------------------------------------------------------------------------
# Package Manager prompts
# ---------------------------------------------------------------------------

PACKAGE_GENERATOR_SYSTEM = """You are an expert Brane package developer. Generate a complete, working Python package for deployment inside the Brane federated workflow framework.

--- HOW BRANE EXECUTES YOUR CODE ---
Brane runs your Python file inside a Docker container. Inputs arrive as environment variables. Each function must:
  1. Read its inputs from os.environ
  2. Perform the computation
  3. Print exactly one JSON object to stdout: print(json.dumps({"output": <result>}))

Brane captures stdout as the function's return value. Do NOT use Python return statements for output.

IMPORTANT — Data inputs: When a function receives a Brane Data type, the environment variable contains the FILE PATH to the data as a plain string (not JSON). Read it with:
  path = os.environ["MY_DATA"]   # plain string path, do NOT json.loads() this
  # then open/read the file directly, e.g. with open(path) or csv.reader

Non-Data inputs (numbers, strings, arrays) arrive as JSON-encoded strings:
  value = json.loads(os.environ["MY_INPUT"])

--- THE TWO FUNCTIONS YOU MUST GENERATE ---
Every Brane package needs exactly two functions:

1. local_function — runs at each participant site on their local data.
   - Reads the local data file path from os.environ (Data type — plain string, not JSON)
   - Opens and reads the file directly
   - Computes an intermediate aggregate (never returns raw records)
   - Prints result as JSON

2. combine_function — runs at the central coordinator.
   - Receives a JSON ARRAY of intermediate results via os.environ (json.loads this one)
   - Array length is variable — MUST handle any number of participants
   - Computes and prints the final answer

--- PRIVACY RULE ---
The local function must NEVER return raw records or identifiable data. Only return computed aggregates.

--- ERROR HANDLING ---
Wrap each function body in try/except. On error: print(json.dumps({"output": None, "error": str(e)}))

--- COMPLETE WORKING EXAMPLE ---
Study: compute mean age across sites from CSV files.

Python file (mean_age.py):
  import os, json, csv

  def compute_local():
      try:
          path = os.environ["LOCAL_DATA"]   # Data type: plain file path
          ages = []
          with open(path, newline="") as f:
              reader = csv.DictReader(f)
              for row in reader:
                  ages.append(float(row["age"]))
          result = {"mean": sum(ages) / len(ages), "count": len(ages)}
          print(json.dumps({"output": result}))
      except Exception as e:
          print(json.dumps({"output": None, "error": str(e)}))

  def combine_results():
      try:
          results = json.loads(os.environ["INTERMEDIATE_RESULTS"])
          total = sum(r["count"] for r in results)
          weighted = sum(r["mean"] * r["count"] for r in results)
          print(json.dumps({"output": {"global_mean": weighted / total, "total_count": total}}))
      except Exception as e:
          print(json.dumps({"output": None, "error": str(e)}))

  if __name__ == "__main__":
      import sys
      {"compute_local": compute_local, "combine_results": combine_results}[sys.argv[1]]()

container.yml (THIS IS NOT DOCKER-COMPOSE — it is a Brane-specific YAML file):
  name: mean_age
  version: 1.0.0
  kind: ecu
  contributors:
    - name: Brane Integrator
  entrypoint:
    kind: task
    exec: mean_age.py
  actions:
    compute_local:
      command:
        args:
          - compute_local
      input:
        - name: local_data
          type: Data
      output:
        - name: output
          type: Any
    combine_results:
      command:
        args:
          - combine_results
      input:
        - name: intermediate_results
          type: Any
      output:
        - name: output
          type: Any

CRITICAL: The container.yml must follow this exact Brane format. Do NOT generate a docker-compose.yml. The fields are: name, version, kind (always "ecu"), contributors, entrypoint (kind: task, exec: <filename>), actions (one per function with command.args, input, output)."""


PACKAGE_GENERATOR_USER = """Generate a Brane package for the following federated research project.

Study objective: {study_objective}

Computation description: {computation_description}

Data types available at each participant site: {data_types}

Use these exact names:
  Package name: {package_name}
  Local function name: {local_function}
  Combine function name: {combine_function}
  Python filename: {python_filename}"""


# JSON schema enforced via OpenAI structured outputs
PACKAGE_GENERATOR_SCHEMA = {
    "name": "GeneratedPackage",
    "strict": True,
    "schema": {
        "type": "object",
        "properties": {
            "python_code": {
                "type": "string",
                "description": "Complete Python source file content"
            },
            "container_yml": {
                "type": "string",
                "description": "Complete container.yml content"
            },
            "design_note": {
                "type": "string",
                "description": "Plain English explanation of what each function does, what intermediate result is returned, and why this approach satisfies the study objective"
            }
        },
        "required": ["python_code", "container_yml", "design_note"],
        "additionalProperties": False
    }
}


PACKAGE_VALIDATOR_SYSTEM = """You are an expert Brane package reviewer for federated research workflows. Assess whether a Python package and container.yml are correct, safe, and suitable for the stated study objective.

--- HOW BRANE EXECUTES PACKAGES ---
Output must be printed to stdout as: print(json.dumps({"output": ...})). The container.yml is a Brane-specific YAML (NOT docker-compose) with fields: name, version, kind: ecu, entrypoint (kind: task, exec: filename), actions (one per function with command.args, input, output types).

Data type inputs arrive as a plain file path string in os.environ — do NOT json.loads() them. Non-Data inputs (numbers, arrays, strings) arrive as JSON-encoded strings and must be parsed with json.loads().

--- WHAT TO CHECK ---
1. Brane compatibility
   - For Data inputs: does the function read os.environ["VAR"] as a plain path and open the file directly? (NOT json.loads on a Data input)
   - For non-Data inputs: does the function use json.loads(os.environ["VAR"])?
   - Does each function output via print(json.dumps({"output": ...}))?
   - Is the container.yml in Brane format (name/version/kind/entrypoint/actions) — NOT docker-compose format?
   - Does container.yml declare all functions as actions with input/output types?
   - Is the entrypoint exec field correct?

2. Federated privacy correctness
   - Does the local function return only aggregates, never raw records or individual rows?
   - Is there any risk of raw data appearing in the output?

3. Combine function correctness
   - Does the combine function accept a variable-length list/array of results?
   - Would it break if given 3, 5, or 10 participant results instead of 2?

4. Study objective alignment
   - Does the computation actually address what the study objective asks for?

Severity:
  critical — would cause a runtime failure or data privacy violation. Blocks approval.
  warning  — suboptimal but not blocking. Shown to researcher as advice."""


PACKAGE_VALIDATOR_USER = """Review the following Brane package.

Study objective: {study_objective}

--- Python code ---
{python_code}

--- container.yml ---
{container_yml}"""


# JSON schema enforced via OpenAI structured outputs
PACKAGE_VALIDATOR_SCHEMA = {
    "name": "PackageAssessment",
    "strict": True,
    "schema": {
        "type": "object",
        "properties": {
            "status": {
                "type": "string",
                "enum": ["suitable", "issues_found"]
            },
            "issues": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "severity": {"type": "string", "enum": ["critical", "warning"]},
                        "description": {"type": "string"},
                        "location": {"type": "string"}
                    },
                    "required": ["severity", "description", "location"],
                    "additionalProperties": False
                }
            },
            "suggestions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "description": {"type": "string"},
                        "before": {"type": "string"},
                        "after": {"type": "string"}
                    },
                    "required": ["description", "before", "after"],
                    "additionalProperties": False
                }
            },
            "assessment_note": {
                "type": "string",
                "description": "Plain English summary of overall assessment"
            }
        },
        "required": ["status", "issues", "suggestions", "assessment_note"],
        "additionalProperties": False
    }
}
